### PR TITLE
PubChem molecules

### PR DESCRIPTION
**Pull request by peastman**
This is a collection of molecules drawn from PubChem.  Here's what I did so far.

I downloaded SDF files for all substance records whose source was either BindingDB or ChemIDplus.  I had to split BindingDB into three files, since they limit each download to 500,000 structures.

processSDFFiles.py reads them in, applies a set of filters, and writes out the IDs and SMILES strings for all passing molecules to a text file.  It keeps substances that satisfy all of these requirements.

- It's only a single molecule
- At least 3 heavy atoms
- No more than 50 atoms total, including hydrogen
- Only these elements: B, Br, C, Ca, Cl, F, H, I, K, Li, Mg, N, Na, O, P, S, Si
- No unpaired electrons
- No isotope specifications
- No sanitization errors

sortMolecules.py reads in those files, combines them, and sorts the molecules so that each one is maximally different from everything that has come before.  The idea is that we will start at the beginning of the list and include as many molecules as we have time for.  I expect that to be at least 10,000, hopefully more.

The sorted list of molecules is in sorted.txt.  Take a look and see whether it seems reasonable.  A consequence of this ordering is that small, exotic molecules tend to get put at the very start of the list.  Within a few hundred molecules, it starts to settle down into much more typical ones.

### CODE REVIEW

**Comment by peastman** [comment]
I've been planning to use OpenFF for generating conformations, but it seems to be a lot more limited in what elements it supports.  Si, Ca, and B aren't supported at all, while Li, Na, K, and Mg are only supported as ions.  I could simply remove them from the filter, but I worry that's overly restrictive.  None of them is that common in drugs, but the numbers aren't negligible.  Out of about 580,000 molecules in this set, Si appears 1960 times and B appears 1545 times.  The others are less common.

Any suggestions?

**Comment by raimis** [comment]
For the initial application, ligand simulations, for sure we need: H, C, N, O, F, P, S, Cl, Br, I. According to our med chem B is getting popular in drugs, so it should be good to have it.

Further, for the protein simulations, we need Se (to cover all the natural amino acids) and cations which make complexes with proteins. The easy ones are: Mg, Ca, Zn. The others (Mn, Fe, Co, Ni, Cu) may be a bit complicated to compute with DFT.

Li, Na, and K don't make any covalent compounds, at least at the biochemical conditions, so they will floating in water. Until we start modelling water with NNP, there is no necessity for them.

 Finally, Si doesn't play any biochemical role as I know.

**Comment by peastman** [comment]
The challenge is how to generate conformations.  We do it with MD, so we need a force field that can model whatever molecules we want to include.  OpenFF doesn't include either B or Se.  I checked GAFF and it doesn't either.  It looks like CGenFF might, at least in some limited cases, but I don't think we have an easy way to use CGenFF in OpenMM.

This collection only includes single molecules, no complexes with ions.  The DES370K collection includes molecules interacting with these ions: Br-, Ca+2, Cl-, F-, I-, K+, Li+, Mg+2, Na+.

**Comment by peastman** [comment]
Here's a [recent article](http://www.pharmacy180.com/article/silicon-based-drugs-versus-carbon-based-analogues-1401/) about drugs containing Si.  A relevant quote:

> Currently, there are only a small number of silicon-containing compounds under investigation for pharma-ceutical use. Silicones are the only silicon-based compounds widely used in medicine. These oligosiloxanes and polysiloxanes have no carbon analogues and they are widely used for plastics, implants, catheters and many other applications.
>
> The limitations of novel organosilicon compounds are very often attributed to insufficient funding and poor evidence of demonstrated efficacy. There is also an on-going debate about the toxicity of silicon-based therapeutics. So far, no increased systematic toxicity of silicon-containing compounds in comparison to their carbon-analogous has been detected.
>
> Nevertheless, several organosilicon compounds have made it to clinical trials. In the following sections, a couple of interesting examples ranging from steroids being used by bodybuilders to anticancer and antispastic drugs under development are presented.

It sounds like this is something we'll eventually want to support, but probably not important for version 1.

**Comment by peastman** [comment]
@jchodera it would be great to get your thoughts on this.

**Comment by peastman** [comment]
Here's what I decided to do.  First, I modified processSDFFiles.py to remove molecules containing Ca, Li, Na, K, and Mg.  They're sufficiently rare and obscure that we don't need to include them.

It looks like we'll eventually want to include molecules with B and Si, but including them in this collection probably wouldn't work well.  We would get so few molecules with each one, it likely wouldn't be enough to learn their chemistry very well.  Instead, we'll want to separately create sets of molecules containing those elements.  So I kept them in processSDFFiles.py, but filtered them out in sortMolecules.py.  So they aren't included here, but we still have lists of molecules from the original sources that we can use to build separate collections.  We'll need to figure out a different way of generating conformations for them.

**Comment by peastman** [comment]
I finished generating conformations for the first 5000 molecules.  It took about two days.  OpenFF was unable to parametrize some, though, so we ended up with 4804 actual molecules.

When I tried to push it to the repository, github that the file was too large.  I'll see if I can get Large File Storage set up.

**Comment by peastman** [comment]
Alternatively I could just split it into two files.  If we have one HDF5 file for every 2500 molecules, that will keep them well under the 100 MB limit.  Using LFS has strict bandwidth limits that I think we could exceed really quickly.

**Comment by peastman** [comment]
I split it into two files and pushed them.  That seems like the easiest solution.  These files are never going to change, so versioning of binary files isn't really an issue.  The individual files are large, but there won't be that many of them.  For v1, the total size of this repository is likely to be under 1 GB.

Let me know if they look ok and I'll do the next 5000.

**Comment by jthorton** [comment]
> OpenFF was unable to parametrize some, though, so we ended up with 4804 actual molecules.

We should keep track of these molecules and share them with OpenFF to look into. 

For the molecules with missing coverage in forcefields we could possibly use [xtb-gfn2](https://pubs.acs.org/doi/10.1021/acs.jctc.8b01176) to generate the conformers and the tools provided in the [xtb package](https://xtb-docs.readthedocs.io/en/latest/contents.html).

**Comment by peastman** [comment]
I processed the next 5000 molecules.  I can keep going, but I don't know how many of these molecules we will want.  It depends on whether we can get permission to include Enamine molecules.  Possibly we should merge this now.  Then I can create a separate PR for additional PubChem molecules if we decide we want them.

**Comment by peastman** [comment]
I went ahead and processed another 5000 molecules.  That's 15,000 total, of which it successfully generated conformation for 14,644.  I think that's plenty for now, so I'll merge this.  We can always do more later if we decide it would be useful.

**Pull request merged**
