### PR TITLE
DES370K dimers

### PR DESCRIPTION
**Pull request by peastman**
This is one of the larger collections (about 360,000 conformations), although it's very quick to generate since we're just converting from one format to another.  I chose not to check in the original DES370K dataset, partly because it's quite big but mainly because it seems like good form to direct people to the official download rather than redistributing it ourselves.

To generate the SMILES strings, I copied the implementation from https://github.com/openforcefield/openff-toolkit/pull/1086.  It ends up only being a few lines.  That way we don't need to wait for a new release of OpenFF Toolkit.

### CODE REVIEW

**Comment by jchodera** [comment]
Are we sure we want to be merging hundreds of files and very large files into GitHub? It handles neither well.

Wouldn't compressed SDFs containing many different molecules in the same SDF be better if we're going to store those?

**Comment by peastman** [comment]
The SDFs are tiny.  They won't be a problem.  Most molecule collections won't have them.  They're part of the input used to generate this collection, and they aren't distributed with the original dataset, so I included them here.

**Comment by jchodera** [comment]
Why do we need a separate SDF for each molecule?

**Comment by peastman** [comment]
It's all described in [the README](https://github.com/openmm/qmdataset/blob/main/des370k/README.md).

**Pull request merged**
